export const CREATE_APARTMENT_SUCCESS = 'CREATE_APARTMENT_SUCCESS';
export const GET_ALL_APARTMENTS_SUCCESS = 'GET_ALL_APARTMENTS_SUCCESS';
export const GET_APARTMENT_BY_ID_SUCCESS = 'GET_APARTMENT_BY_ID_SUCCESS';
export const UPDATE_APARTMENT_SUCCESS = 'UPDATE_APARTMENT_SUCCESS';
export const DELETE_APARTMENT_SUCCESS = 'DELETE_APARTMENT_SUCCESS';